build:
	sudo docker build -f ./Dockerfile -t syunkitada/centos7-influxdb:latest .

build_0.9:
	sudo docker build -f ./Dockerfile -t syunkitada/centos7-influxdb:latest .

login:
	sudo docker login

push:
	sudo docker push syunkitada/centos7-influxdb
